/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scicalculation;

/**
 *
 * @author HP 15
 */
public class scicalci extends javax.swing.JFrame {
     double firstnum;
     double secondnum;
     double result;
     String operations;
     private Object math;
    
    
    public scicalci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton30 = new javax.swing.JButton();
        jtxtDisplay = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        som7 = new javax.swing.JButton();
        som8 = new javax.swing.JButton();
        som4 = new javax.swing.JButton();
        som5 = new javax.swing.JButton();
        som1 = new javax.swing.JButton();
        som2 = new javax.swing.JButton();
        som0 = new javax.swing.JButton();
        somdot = new javax.swing.JButton();
        som3 = new javax.swing.JButton();
        somdivide = new javax.swing.JButton();
        sompluMinus = new javax.swing.JButton();
        somequal = new javax.swing.JButton();
        som9 = new javax.swing.JButton();
        somminus = new javax.swing.JButton();
        som6 = new javax.swing.JButton();
        sommul = new javax.swing.JButton();
        sombkspace = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        root = new javax.swing.JButton();
        somplus = new javax.swing.JButton();
        somlog = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        sinh = new javax.swing.JButton();
        pie = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        cosh = new javax.swing.JButton();
        round = new javax.swing.JButton();
        xy1 = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        tanh = new javax.swing.JButton();
        xy2 = new javax.swing.JButton();
        cube = new javax.swing.JButton();
        hex = new javax.swing.JButton();
        xy3 = new javax.swing.JButton();
        bin = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jCheckBox1.setText("jCheckBox1");

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton30.setText("Sinh");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        som7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som7.setText("7");
        som7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som7ActionPerformed(evt);
            }
        });

        som8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som8.setText("8");
        som8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som8ActionPerformed(evt);
            }
        });

        som4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som4.setText("4");
        som4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som4ActionPerformed(evt);
            }
        });

        som5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som5.setText("5");
        som5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som5ActionPerformed(evt);
            }
        });

        som1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som1.setText("1");
        som1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som1ActionPerformed(evt);
            }
        });

        som2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som2.setText("2");
        som2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som2ActionPerformed(evt);
            }
        });

        som0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som0.setText("0");
        som0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som0ActionPerformed(evt);
            }
        });

        somdot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somdot.setText(".");
        somdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somdotActionPerformed(evt);
            }
        });

        som3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som3.setText("3");
        som3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som3ActionPerformed(evt);
            }
        });

        somdivide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somdivide.setText("/");
        somdivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somdivideActionPerformed(evt);
            }
        });

        sompluMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sompluMinus.setText("+-");
        sompluMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sompluMinusActionPerformed(evt);
            }
        });

        somequal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somequal.setText("=");
        somequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somequalActionPerformed(evt);
            }
        });

        som9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som9.setText("9");
        som9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som9ActionPerformed(evt);
            }
        });

        somminus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somminus.setText("-");
        somminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somminusActionPerformed(evt);
            }
        });

        som6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        som6.setText("6");
        som6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                som6ActionPerformed(evt);
            }
        });

        sommul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sommul.setText("*");
        sommul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sommulActionPerformed(evt);
            }
        });

        sombkspace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sombkspace.setText("<-");
        sombkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sombkspaceActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("C");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        root.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        root.setText("Rt");
        root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootActionPerformed(evt);
            }
        });

        somplus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somplus.setText("+");
        somplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somplusActionPerformed(evt);
            }
        });

        somlog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        somlog.setText("log");
        somlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somlogActionPerformed(evt);
            }
        });

        sin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sin.setText("Sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        sinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sinh.setText("Sinh");
        sinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhActionPerformed(evt);
            }
        });

        pie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pie.setText("Pie");
        pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieActionPerformed(evt);
            }
        });

        cos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cos.setText("Cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        cosh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cosh.setText("Cosh");
        cosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coshActionPerformed(evt);
            }
        });

        round.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        round.setText("Round");
        round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundActionPerformed(evt);
            }
        });

        xy1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xy1.setText("X^Y");
        xy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xy1ActionPerformed(evt);
            }
        });

        tan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tan.setText("Tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        tanh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanh.setText("Tanh");
        tanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanhActionPerformed(evt);
            }
        });

        xy2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xy2.setText("X^2");
        xy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xy2ActionPerformed(evt);
            }
        });

        cube.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cube.setText("cu");
        cube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeActionPerformed(evt);
            }
        });

        hex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hex.setText("Hex");
        hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexActionPerformed(evt);
            }
        });

        xy3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xy3.setText("X^3");
        xy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xy3ActionPerformed(evt);
            }
        });

        bin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bin.setText("Bin");
        bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Standard");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Scientific");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtDisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sombkspace, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(somplus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(som7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(som8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(som4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(som5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(som1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(som2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(som0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(somdot, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(som3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(somdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sompluMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(somequal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(som6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sommul, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(som9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(somminus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(xy3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(bin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(xy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(xy2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cube, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tan))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hex, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(round, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(somlog)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(somplus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sombkspace, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(som9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(somminus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pie, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(som6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sommul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(xy1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tanh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(som3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(somdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(xy2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cube, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(round, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(xy3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(hex, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(sompluMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(somequal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(som7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(som8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(som4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(som5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(som1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(som2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(som0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(somdot, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(somlog, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       
        
                
        this.setResizable(true);
       this.setSize(250, 450);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      this.setResizable(true);
       this.setSize(500, 450); 
       jtxtDisplay.setSize(450,40);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.setResizable(true);
       this.setSize(250,450);
       
       
        
    }//GEN-LAST:event_formWindowActivated

    private void som7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som7ActionPerformed
       String iNum = jtxtDisplay.getText() + som7.getText();
       jtxtDisplay.setText(iNum);
       
        
    }//GEN-LAST:event_som7ActionPerformed

    private void som8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som8ActionPerformed
       String iNum = jtxtDisplay.getText() + som8.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here:
    }//GEN-LAST:event_som8ActionPerformed

    private void som4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som4ActionPerformed
String iNum = jtxtDisplay.getText() + som4.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here        // TODO add your handling code here:
    }//GEN-LAST:event_som4ActionPerformed

    private void som5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som5ActionPerformed
       String iNum = jtxtDisplay.getText() + som5.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here // TODO add your handling code here:
    }//GEN-LAST:event_som5ActionPerformed

    private void som1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som1ActionPerformed
        String iNum = jtxtDisplay.getText() + som1.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here// TODO add your handling code here:
    }//GEN-LAST:event_som1ActionPerformed

    private void som2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som2ActionPerformed
       String iNum = jtxtDisplay.getText() + som2.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here // TODO add your handling code here:
    }//GEN-LAST:event_som2ActionPerformed

    private void som0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som0ActionPerformed
       String iNum = jtxtDisplay.getText() + som0.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here // TODO add your handling code here:
    }//GEN-LAST:event_som0ActionPerformed

    private void somdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somdotActionPerformed
        if(! jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText() + somdot.getText());
        }
        

        
    }//GEN-LAST:event_somdotActionPerformed

    private void som3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som3ActionPerformed
       String iNum = jtxtDisplay.getText() + som3.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here // TODO add your handling code here:
    }//GEN-LAST:event_som3ActionPerformed

    private void somdivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somdivideActionPerformed
firstnum = Double.parseDouble(jtxtDisplay.getText());
    jtxtDisplay.setText(null);
    operations = ("/");    // TODO add your handling code here:
    }//GEN-LAST:event_somdivideActionPerformed

    private void sompluMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sompluMinusActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops * (-1);
        
         jtxtDisplay.setText(String.valueOf(ops));        
        
        
    }//GEN-LAST:event_sompluMinusActionPerformed

    private void somequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somequalActionPerformed
     String answer;
     secondnum = Double.parseDouble(jtxtDisplay.getText());
     if(operations == "+")
     {
         result = firstnum + secondnum;
         answer = String.format("%.2f",result);
         jtxtDisplay.setText(answer);
     
       }
     
     else if(operations == "-")
     {
         result = firstnum - secondnum;
         answer = String.format("%.2f",result);
         jtxtDisplay.setText(answer);
     
       }
     
     else if(operations == "*")
     {
         result = firstnum * secondnum;
         answer = String.format("%.2f",result);
         jtxtDisplay.setText(answer);
     }
     
     else if(operations == "/")
     {
         result = firstnum / secondnum;
         answer = String.format("%.2f",result);
         jtxtDisplay.setText(answer);
     }
     
     
    }//GEN-LAST:event_somequalActionPerformed

    private void som9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som9ActionPerformed
String iNum = jtxtDisplay.getText() + som9.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here        // TODO add your handling code here:
    }//GEN-LAST:event_som9ActionPerformed

    private void somminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somminusActionPerformed
firstnum = Double.parseDouble(jtxtDisplay.getText());
    jtxtDisplay.setText(null);
    operations = ("-");
    }//GEN-LAST:event_somminusActionPerformed

    private void som6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_som6ActionPerformed
       String iNum = jtxtDisplay.getText() + som6.getText();
       jtxtDisplay.setText(iNum); // TODO add your handling code here // TODO add your handling code here:
    }//GEN-LAST:event_som6ActionPerformed

    private void sommulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sommulActionPerformed
firstnum = Double.parseDouble(jtxtDisplay.getText());
    jtxtDisplay.setText(null);
    operations = ("*");    // TODO add your handling code here:
    }//GEN-LAST:event_sommulActionPerformed

    private void sombkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sombkspaceActionPerformed
       String bsp = null;
       
       if(jtxtDisplay.getText().length() > 0)
       {
           StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
           strB.deleteCharAt(jtxtDisplay.getText().length() -1);
           bsp = strB.toString();
           jtxtDisplay.setText(bsp);
       }
        
    }//GEN-LAST:event_sombkspaceActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
      
       jtxtDisplay.setText(""); // TODO add your handling code here // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootActionPerformed
 double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sqrt(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));             
        
    }//GEN-LAST:event_rootActionPerformed

    private void somplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somplusActionPerformed
    firstnum = Double.parseDouble(jtxtDisplay.getText());
    jtxtDisplay.setText(null);
    operations = ("+");
    }//GEN-LAST:event_somplusActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void somlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somlogActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.log(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));    
    }//GEN-LAST:event_somlogActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sin(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));    
    }//GEN-LAST:event_sinActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void sinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhActionPerformed
 double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sinh(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));    
    }//GEN-LAST:event_sinhActionPerformed

    private void pieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieActionPerformed
        double ops;// = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (3.141525358979367987);
        
         jtxtDisplay.setText(String.valueOf(ops));    // TODO add your handling code here:
    }//GEN-LAST:event_pieActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cos(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));    // TODO add your handling code here:
    }//GEN-LAST:event_cosActionPerformed

    private void coshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coshActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cosh(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));    // TODO add your handling code here:
    }//GEN-LAST:event_coshActionPerformed

    private void roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.round(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));  // TODO add your handling code here:
    }//GEN-LAST:event_roundActionPerformed

    private void xy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xy1ActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.pow(ops, ops);
        
         jtxtDisplay.setText(String.valueOf(ops));     // TODO add your handling code here:
    }//GEN-LAST:event_xy1ActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.tan(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));            // TODO add your handling code here:
    }//GEN-LAST:event_tanActionPerformed

    private void tanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanhActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.tanh(ops);
        
         jtxtDisplay.setText(String.valueOf(ops));     // TODO add your handling code here:
    }//GEN-LAST:event_tanhActionPerformed

    private void xy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xy2ActionPerformed
       double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops * ops);
        
         jtxtDisplay.setText(String.valueOf(ops));   // TODO add your handling code here:
    }//GEN-LAST:event_xy2ActionPerformed

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cbrt(ops);
        
         jtxtDisplay.setText(String.valueOf(ops)); // TODO add your handling code here:
    }//GEN-LAST:event_cubeActionPerformed

    private void hexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexActionPerformed
       int a = Integer.parseInt(jtxtDisplay.getText());
      jtxtDisplay.setText(Integer.toString(a,16)); // TODO add your handling code here:
    }//GEN-LAST:event_hexActionPerformed

    private void xy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xy3ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = (ops * ops * ops);
        
         jtxtDisplay.setText(String.valueOf(ops)); // TODO add your handling code here:
    }//GEN-LAST:event_xy3ActionPerformed

    private void binActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binActionPerformed
      int a = Integer.parseInt(jtxtDisplay.getText());
      jtxtDisplay.setText(Integer.toString(a,2));
      
        // TODO add your handling code here:
    }//GEN-LAST:event_binActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scicalci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bin;
    private javax.swing.JButton cos;
    private javax.swing.JButton cosh;
    private javax.swing.JButton cube;
    private javax.swing.JButton hex;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton30;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JButton pie;
    private javax.swing.JButton root;
    private javax.swing.JButton round;
    private javax.swing.JButton sin;
    private javax.swing.JButton sinh;
    private javax.swing.JButton som0;
    private javax.swing.JButton som1;
    private javax.swing.JButton som2;
    private javax.swing.JButton som3;
    private javax.swing.JButton som4;
    private javax.swing.JButton som5;
    private javax.swing.JButton som6;
    private javax.swing.JButton som7;
    private javax.swing.JButton som8;
    private javax.swing.JButton som9;
    private javax.swing.JButton sombkspace;
    private javax.swing.JButton somdivide;
    private javax.swing.JButton somdot;
    private javax.swing.JButton somequal;
    private javax.swing.JButton somlog;
    private javax.swing.JButton somminus;
    private javax.swing.JButton sommul;
    private javax.swing.JButton sompluMinus;
    private javax.swing.JButton somplus;
    private javax.swing.JButton tan;
    private javax.swing.JButton tanh;
    private javax.swing.JButton xy1;
    private javax.swing.JButton xy2;
    private javax.swing.JButton xy3;
    // End of variables declaration//GEN-END:variables
}
